### ISSUE TITLE
Write-only default box

### ISSUE THREAD

**Issue by mciszczon** [cdgriffith/Box#100]
Hi!

First of all, thank you very much for this neat library, it really comes in handy in a project I'm currently working on, but I've stumbled upon one case that is currently not handled by Box.

It's something that I called `write_default_box`. Its behavior would be similar to the default box, but only when trying to set an attribute. When trying to simply get an attribute that does not exists, it would still return `BoxKeyError`.

I'm willing to work on this and propose a pull request, but first I wanted to consult you and ask whether you see a possibility to implement something like this and so on.

Thanks for your time!

--- 

An example of how this new behavior would work is below:

```python

> box = Box(writeonly_default_box=True)
> box

Box({})

> box.nested.field

BoxKeyError: "'Box' object has no attribute 'test'"

> box.nested.field = "value"
> box

Box({
	"nested": {
		"field": "value"
	}
})
```

**Comment by cdgriffith** [comment]
That's a cool idea! I never envisioned that usage myself, but would gladly add that if you put in a PR for it! 

(Can also work on it when I get a moment myself, but no promises on turnaround time lol)

**Comment by mciszczon** [comment]
@cdgriffith Sure enough, thanks for the quick response! I'll also try to take a look into it and implement the feature—I'll keep you updated on this.

**Comment by cdgriffith** [comment]
I looked into this a few times to try and get it into 4.0, but the main issue is that the first thing that happens during trying to set the value is actually the `__getattr__` of the first sub Box, and there is no context given for it to know that eventually a value is going to be set. 

I don't know of any way to have this work without some sort of wrapper function.

**Comment by cdgriffith** [comment]
If anyone thinks of a way to actually achieve this it can be re-addressed, but I don't know if it's reasonably possible.
