### ISSUE TITLE
Bug when popping keys that contain twice-nested dicts before viewing an object's `repr()`

### ISSUE THREAD

**Issue by jlowin** [cdgriffith/Box#102]
Hi, I recently came across `Box` and am excited to adopt it for Prefect (see https://github.com/PrefectHQ/prefect/pull/1518). However, one of our unit tests highlighted what appears to be an odd bug.

The following code results in a `BoxKeyError`:
```
from box import Box

x = Box({"a": {"b": {"c": 1}}})

# error
x.pop('a')

# calling repr works (or just examining the object)
x = Box({"a": {"b": {"c": 1}}})
repr(x)
x.pop('a')

# happens for any twice-nested key
Box({"a": {"b": {"c": {'d':1}}}}).a.pop('b') #error
```

Basically, if you try to `pop` a key that has two nested keys under it, you get an error.

What makes this really weird and Heisenbug-ish is that if you inspect the `Box` object interactively or even call `repr()` on it, everything works fine. I don't know Box well enough to trace the error yet but it seems to be some deferred initialization of the recursive Box objects -- maybe in the `_box_heritage` tracker?

I hope this example helps track down the problem.

**Comment by cicdw** [comment]
It appears that the pop is actually successful prior to the error:
```python
from box import Box

x = Box({"cat": {"alive": {"dead": True}}}) 
x.pop("cat") # error

repr(x) # <Box: {}>
```
but if you call `repr` _first_, the pop is successful without error.

**Comment by cdgriffith** [comment]
Thanks for the error report, confirmed I can reproduce.

This looks to be due to the popped `Box` object retaining now removed history from it's special config variable.  Quick fix is to just reset `__box_heritage` to `()` on pop, but I need to do an exploration to see what else this may affect as well with fresh eyes tomorrow.

```
from box import Box

x = Box({"a": {"b": {"c": 1}}})
g = x.pop('a')

print(g._box_config['__box_heritage'])
# (<Box: {}>, 'a')

print(g) # `__str__` converts it to a dict for easy printing, and in the process breaks
# KeyError: 'a'

```

Thanks again!

**Comment by jlowin** [comment]
Thanks for the quick response!
