### ISSUE TITLE
del() does not accept snake case attribute names when calling it on a camel-killer box

### ISSUE THREAD

**Issue by iordanivanov** [cdgriffith/Box#111]
I'm not really sure if this is intended or not, but I'm unable to delete attributes from a camel-killer box by referring to them with their snake case name.

I'm using Python 3.7.3 (with Anaconda 3), on Ubuntu 18.04.3 LTS

Trying to delete an attribute by referring to it with its camel case name:
![2019-11-19-144056_860x352_scrot](https://user-images.githubusercontent.com/15002638/69147616-568d6500-0aca-11ea-97c3-d8b3301d0c5c.png)

Trying to delete an attribute by referring to it with its snake case name:
![2019-11-19-144139_932x626_scrot](https://user-images.githubusercontent.com/15002638/69147565-2e056b00-0aca-11ea-8c21-dbb4c604430f.png)

**Comment by cdgriffith** [comment]
Thanks for bringing that to my attention, I would consider that unexpected behavior.

**Comment by cdgriffith** [comment]
Fixed in 4.0
