### ISSUE TITLE
Remove pytest-runner

### ISSUE THREAD

**Issue by henryk** [cdgriffith/Box#115]
Line https://github.com/cdgriffith/Box/blob/6d8790e35b6d2f20eb3bb0f4b450b0413daa94c1/setup.py#L36 should be removed.

Issue 1 (my immediate one): I'm using automated builds for an embedded device and the build environment is minimal, and doesn't include pytest. Since I'm not testing.
Issue 2: https://pypi.org/project/pytest-runner/#deprecation-notice

**Comment by cdgriffith** [comment]
Fixed in 4.0
