### ISSUE TITLE
Regression due to ruamel.yaml

### ISSUE THREAD

**Issue by wimglenn** [cdgriffith/Box#127]
Potentially dangerous regression in config box, due to the new `ruamel.yaml` dependency.

```
>>> from box import ConfigBox
>>> b = ConfigBox.from_yaml("kill_all_humans_mode: no")
>>> if b.kill_all_humans_mode: 
...     print("ok, killing all humans...") 
...
ok, killing all humans...
```

Same problem with `box.Box`. Our test suite caught this, but others might not be so lucky.  [ruamel isn't exactly a drop-in replacement for yaml](https://yaml.readthedocs.io/en/latest/pyyaml.html#differences-with-pyyaml), despite claims to the contrary (ruamel defaults to spec 1.2 and yaml is spec 1.1).

I would advise to make the `toml` and `ruamel.yaml` dependencies optional (or "soft" dependencies, like it was in 3.x) since users might prefer other providers such as `pytoml` and `PyYAML` and you don't want to tie their hands here. 

Personally, I can not use `box>=4` at all because the `ruamel.yaml` has an [insane installer](https://bitbucket.org/ruamel/yaml/src/default/setup.py) which, for various reasons, does not work in the prod environment at $EMPLOYER.

**Comment by cdgriffith** [comment]
For `ruamel.yaml` it is possible to use version 1.1 by passing that argument to the loader which should remove any differences that I am aware of.

```
Box.from_yaml("kill_all_humans_mode: no", version='1.1')
<Box: {'kill_all_humans_mode': False}>
```

I am against the soft dependencies as it makes it more cumbersome for the 95% percent case, and also makes it so dependencies like that can exist due to external libraries (aka with Box 3.x if someone has `PyYAML` on one machine and `ruamel.yaml` on another can produce different results.) 

However, as there is no way to monkey patch `PyYAML` in without having `ruamel.yaml` imported successfully that does cause a conundrum in the case where one cannot install `ruamel.yaml` at all. I will need to think of a way to allow for fallbacks if those other dependencies are already on the system, or somehow manually flagged to use instead of the defaults.

**Comment by cdgriffith** [comment]
Testing this out https://github.com/cdgriffith/Box/commit/92439a7889ac493e3aa9b3d80565d0efac53ed9a 

I can't think of an easy way other than checking on install if `PyYAML` is alraedy installed and `ruamel.yaml` is not. I am going to sleep on this, but let me know if you have any other ideas for it! 

Also not planning to bother to do that to `toml` as `pytoml` is depreciated. 

To be honest when working on 4.x initially, before the [PyYAML 5.1 release](https://pyyaml.org/wiki/PyYAML), I was blindly assuming that we wasn't going to see another major release, so it's nice to see that both projects are still alive and well!

**Comment by wimglenn** [comment]
https://github.com/cdgriffith/Box/commit/92439a7889ac493e3aa9b3d80565d0efac53ed9a is really not the right way to go about it. Since you are shipping [.whl](https://pypi.org/project/python-box/#files) distributions, the `setup.py` is typically not executed at all for the end user. The distribution dependencies are determined at build time, not at install time (unless you're shipping source distributions _only_, forcing the end user to execute a `setup.py` at install time).

Maybe it's best to just make the toml/yaml supported as optional "extras". Perhaps not every user even wants these features, and just wants to use `Box` in pure Python without loading from markup language.

Then the syntax for end user will look like this:

```
pip install python-box  # pure python version
pip install python-box[yaml]   # with yaml support
pip install python-box[toml]  # with toml support
pip install python-box[toml,yaml]  # with both yaml and toml support
```

This allows you to choose your preferred yaml/toml providers in the metadata, but also allows users who have some other preference to use some other one without getting a dependency conflict.

**Comment by cdgriffith** [comment]
I actually have not seen that syntax / usage before. How do you access or use that metadata info? (Have a handy link with examples perhaps?) 

Thanks!

**Comment by wimglenn** [comment]
See https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by cdgriffith** [comment]
As this is really outside the normal use case, how I think it is best to handle it is allow to fallback to PyYAML, with a warning, when ruamel is not detected. Will require to be installed with --no-deps and manual install of toml and PyYAML. https://github.com/cdgriffith/Box/commit/1eb54789393063093de4ad1847cabbb51efc2d3b#diff-e414a41f99d33494f17b4d6dfdcaac57

**Comment by wimglenn** [comment]
Would you be able to change the `warnings.warn` into a log event, at level INFO or DEBUG? It is not usual to have a warning raised during normal use-cases (and in some environments these warnings are configured to escalate into exceptions).

**Comment by cdgriffith** [comment]
The fact there is no opt out method is the real killer here. Or even for setup / wheel to have a 'or' option for requirements would be ideal. 

`PyYAML` does not support the newer standard 1.2, and `ruamel.yaml` handles both 1.1 and 1.2 is why it was chosen as the standard. I wanted to aim with Box 4 to not have discrepancies between installs, and to have all features available out of the box, hence the new requirements. 

If the backup to PyYAML import is to stay, it will need the warning yes. As it is a clear variant from the default behavior, which if expected, can be [properly ignored beforehand](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings).  (Will create a `BoxWarning` in the `exceptions` file, subclass of `UserWarning`)

**Comment by wimglenn** [comment]
Though the PyYAML project has not been maintained very reliably, it's possible that it will support 1.2 in a later release. Regardless, I think handling both 1.1 and 1.2 is not necessarily the only important consideration here: there is also ruamel's [`Bad performance compared to PyYAML`](https://bitbucket.org/ruamel/yaml/issues/159/bad-performance-compared-to-pyyaml) - that reporter shows 300%-2500% slowdown, on my machine it is not so bad but ruamel is still approx 2x slower than yaml. I've worked on several projects where parsing large yaml files was already a bottleneck on the fast path, even with the C loaders, and performance is very much a consideration when choosing a yaml loader.

There is no need to release the warning/fallback version (at least not for my purposes) because I will rather constrain to `python-box~=3.4.6` than search a hack way to opt-out of required dependency and suppress warning at import time.

Please mention in `CHANGES.rst` exactly where the default parser has changed from 1.1 to 1.2 (was this was in 4.0.0?)

**Comment by cdgriffith** [comment]
Adding details in the CHANGES and the 4.x_changes files: https://github.com/cdgriffith/Box/commit/5655db8593f5e67b5374e44240a26e500b4926ef

**Comment by cdgriffith** [comment]
documentation updates slated for 4.1 https://github.com/cdgriffith/Box/pull/132

**Comment by cdgriffith** [comment]
Addressed in [4.1.0](https://github.com/cdgriffith/Box/tree/4.1.0)

**Comment by cdgriffith** [comment]
As an update to this, Box 5.0 will go back to being able to be pure python, and installing additional extras as requested.  https://github.com/cdgriffith/Box/wiki/Installation

**Comment by wimglenn** [comment]
@cdgriffith  Great, thanks for the update. Are you planning to also change the various `BoxWarning` into log events to go along with this change? It's common practice to escalate warnings into exceptions in dev environments, and having to ignore `BoxWarning` to avoid the too-eager check for _optional_ dependencies is a little annoying, though not a deal-breaker.

**Comment by cdgriffith** [comment]
As they might cause other side effects for programs not prepared for stdout, I was planning on removing them in the  next point release soon. Just needed a way to give a heads up to early adopters  (or who dont version lock) who could have easily overlooked the change.
