### ISSUE TITLE
Box.update is slow

### ISSUE THREAD

**Issue by jkylling** [cdgriffith/Box#129]
Is Box.update supposed to be much slower than dict.update? I expected the performance to be comparable, and ran into trouble. The code below shows the timing for dict.update and Box.
.update

```python
import random
import box
import string
import time

def random_string(N):
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=N))


a = dict((random_string(64), 0) for i in range(10**3))
for i in a:
    a[i.upper()] = 0

b = box.Box(dict((random_string(64), 0) for i in range(10)))
c = dict((random_string(64), 0) for i in range(10))

st = time.time()
c.update(a)
et = time.time()
print(et - st)

st = time.time()
b.update(a)
et = time.time()
print(et - st)
```
Output:
```
2.09808349609375e-05
4.840667724609375
```
With
```
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
```

**Comment by cdgriffith** [comment]
The slowdown is because on an update each and every item being added to the Box has to be evaluated and possibly converted, such as when a `dict` or `list` is in the update. Which means it can't use the built-in `update` method, making it a lot slower.

**Comment by jkylling** [comment]
The above was tested with Box 3.4.6, while in 4.0.4 `Box.update` is closer to `dict.update` and the performance is much better. Sorry for the confusion. The 3.4.6 version of `Box.update` lives on in `Box.merge_update`. For `Box.merge_update` the performance is still very slow, the same as for the old `Box.update` in 3.4.6. See the code below. This performance issue is a consequence of `__setattr__` being slow because of `_conversion_checks` iterating over all keys in the dictionary on every call of `__setattr__`. This also seems to be the case for `__delitem__`, and `__getattr__`. In practice this means that the basic operations (creates, lookup, updates, deletions) of `Box` have the same performance as a list. The below code shows that merge_update is considerably slower than `dict.update` in 4.0.4.

By using some extra internal bookkeeping data in `Box` it is possible to get performance comparable to `dict`.

```python
import random
import box
import string
import time

def random_string(N):
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=N))


a = dict((random_string(64), 0) for i in range(10**2))
for i in a:
    a[i.upper()] = 0

b = box.Box(dict((random_string(64), 0) for i in range(10**3)))
c = dict((random_string(64), 0) for i in range(10**3))

st = time.time()
c.update(a)
et = time.time()
print(et - st)

st = time.time()
b.merge_update(a)
et = time.time()
print(et - st)
timing.py (END)
```

**Comment by cdgriffith** [comment]
Thank you so much for looking into this more. I was literally working on this last night and today, and after looking into optimizations have already made some big speed ups for regular creation and updates on develop https://github.com/cdgriffith/Box/compare/development 

I will be going through and added in your PR changes shortly, just going to change to different branch and incorporate by hand as a heads up as there was a major release yesterday that would cause a headache of a conflict resolve.

**Comment by cdgriffith** [comment]
If you could test out commit https://github.com/cdgriffith/Box/commit/ed271ae0662c6b85ff465f49ec3779eebd9ce595 would be appreciated! 

Quick install for development branch (in case of more updates) 
```
pip install git+https://github.com/cdgriffith/Box.git@development
```
or that commit specifically
```
pip install git+https://github.com/cdgriffith/Box.git@ed271ae0662c6b85ff465f49ec3779eebd9ce595 
```

**Comment by jkylling** [comment]
Thanks! This fixes the main issue for most common operations. `merge_update` is now much quicker. Still you can probably make box even faster.

As a user, I would expect the cost of `__getattr__` and `__getitem__` to be comparable (same for `__setattr__` and `__setitem__`, and `__delattr__` and `__delitem__`). With the current implementation the complexity of `__getattr__` is O(number_of_keys * typical_key_length) while that of `__getitem__` is O(log(number_of_keys)). An unsuspecting user might decide to use `__getattr__` instead of `__getitems__` and experience much worse performance.

The problems are `_attr_lookup` and `_conversion_checks` which iterate over all keys, and convert them to safe keys, on every call. If you add a bit more bookkeeping to the Box code this overhead can be avoided. A sketch of how to do this is in https://github.com/cdgriffith/Box/pull/134

For every `(key, value)` added or removed to the box you need to keep track of `(safe_key, key)` in a dictionary, let's call it `safe_key_store`. For a new attribute `key` you only have to lookup its associated `safe_key` in `safe_key_store` in the functions `_attr_lookup` or in `_conversion_checks`. This reduced the number of operations in this method from requiring O(number_of_keys * typical_key_length) operations to requiring O(log(number_of_keys)) operations. With the recent refactoring you have done this addition should be feasible. Please tell me if you want any example code showing this difference in performance?

**Comment by cdgriffith** [comment]
I am actually working through your stuff now to make sure I grok it and then implement it right. Just wanted to quickly address the `merge_update` specific issue first, as it shouldn't have even been calling `__setattr__` anymore with the 4.x update. 

I am also working on a thorough benchmark / report that I plan to run as part of testing to make sure stuff like this gets discovered faster. 

Thank you for your hard work on this, as well as good write up for the details!

**Comment by jkylling** [comment]
Great! Looking forward to the new implementation. I would be happy to review it if you want any feedback.

**Comment by cdgriffith** [comment]
Have a few more cleanup / fixes to do (realized now delete needs to operate a bit different) but https://github.com/cdgriffith/Box/commit/4c12c44c5123d36cf3c9f37218f7282a75bd9c6c should have the bases of the new safe key store. I took some simplifications to it, making it only a mapping of `safe_key`:`original_key` and such, but makes a large improvement!

Also working on a benchmark / report file if you want something easy to run, just requires `box` and `requests`. Pretty ugly at the moment, but hopefully functional. 

<details>
  <summary>Benchmark Script </summary>
  
```python
import time
import os
import json
from pathlib import Path
import random
import string
import sys
import platform
import multiprocessing
from datetime import datetime
from pprint import pprint

import requests
try:
    from ruamel import yaml
    yaml_lib = 'ruamel.yaml'
except ImportError:
    import yaml
    yaml_lib = 'PyYAML'
import toml

from box import Box
import box

def timer(func, *args, **kwargs):
    start_time = time.perf_counter()
    func(*args, **kwargs)
    return float(f'{time.perf_counter() - start_time:.6f}')

def lookup(obj):
    for k in obj:
        obj[k]

def get_lookup(obj):
    for k in obj:
        obj.get(k)

def box_insert(bx):
    for i in range(1_000):
        bx["new {}".format(i)] = {'a': i}

def attr_lookup(obj):
    for k in obj:
        getattr(obj, k)

def pop(obj, items):
    for k in items:
        obj.pop(k)

def delete(obj, items):
    for k in items:
        del obj[k]

def delete_attr(obj, items):
    for k in items:
        delattr(obj, k)

def set_item(obj, sl, il):
    for i, key in enumerate(sl):
        obj[key] = il[i]

def set_attr(obj, sl, il):
    for i, key in enumerate(sl):
        setattr(obj, key, il[i])

def random_string():
    return ''.join(random.choices(string.printable + string.digits, k=random.randint(5,40)))

test = dict((random_string(), 0) for i in range(1_000))
merge_update_dict = dict((random_string(), 0) for i in range(1_000))
update_dict = dict((random_string(), 0) for i in range(1_000))
set_list = [random_string() for _ in range(1000)]
set_attr_list = [random_string() for _ in range(1000)]
item_list = [random_string() for _ in range(1000)]

card_version = '25770'
card_cache = Path(os.path.dirname(__file__), f'hearthstone_{card_version}.json')
report_name = Path(os.path.dirname(__file__), f'box_{box.__version__}_report_{datetime.now().isoformat().replace(":", "-")}.json')
if not card_cache.exists():
    print("Downloading hearthstone card data")
    req = requests.get(f"https://api.hearthstonejson.com/v1/{card_version}/all/cards.json")
    print(f"Download complete, saving to cache file {card_cache}")
    data = {'cards': req.json()}
    card_cache.write_text(json.dumps(data))
    print("Data saved locally for faster")
else:
    data = json.loads(card_cache.read_text())
data.update(test)

start_time = time.perf_counter()
my_box = Box(data)
load_time = time.perf_counter() - start_time


results = Box(
    benchmarks = Box(
    load=load_time,
    lookup=timer(lookup, my_box),
    get_lookup=timer(get_lookup, my_box),
    attr_lookup=timer(attr_lookup, my_box),
    insert_1000=timer(box_insert, my_box),
    merge_update_1000=timer(my_box.merge_update, merge_update_dict),
    update_1000=timer(my_box.update, update_dict),
    pop=timer(pop, my_box, merge_update_dict.keys()),
    delete=timer(delete, my_box, update_dict.keys()),
    delete_attr=timer(delete_attr, my_box, test.keys()),
    set_item=timer(set_item, my_box, set_list, item_list),
    set_attr=timer(set_attr, my_box, set_attr_list, item_list)
    #to_json=timer(my_box.to_json),
    #to_yaml=timer(my_box.to_yaml),
    #to_dict=timer(my_box.to_dict),
    ),
    settings = Box(
        box_version=box.__version__,
        hearthstone_card_version=card_version,
        yaml_library=yaml_lib,
        yaml_version= yaml.__version__,
        toml_version=toml.__version__
    ),
    machine_specs = Box(
        python_version=".".join(str(x) for x in list(sys.version_info)[:3]),
        python_compiler=platform.python_compiler(),
        python_implimentation=platform.python_implementation(),
        arch=platform.architecture(),
        processor=platform.processor(),
        cpu_count=multiprocessing.cpu_count()
    )
)

pprint(results)
# results.to_json(filename=str(report_name), indent=2)
```
</details>

Without your optimizations:

```
'benchmarks': {'attr_lookup': 0.000888,
                'delete': 0.001119,
                'delete_attr': 5.900524,
                'get_lookup': 0.000528,
                'insert_1000': 0.01397,
                'load': 0.6055709,
                'lookup': 0.000362,
                'merge_update_1000': 0.002017,
                'pop': 0.001642,
                'set_attr': 11.308935,
                'set_item': 0.001799,
                'update_1000': 0.000556},
```

With optimizations: 
```
{'benchmarks': {'attr_lookup': 0.000873,
                'delete': 0.001131,
                'delete_attr': 0.002048,
                'get_lookup': 0.000527,
                'insert_1000': 0.029621,
                'load': 2.2037578,
                'lookup': 0.000364,
                'merge_update_1000': 0.012044,
                'pop': 0.001657,
                'set_attr': 0.01459,
                'set_item': 0.011969,
                'update_1000': 0.010393},
```
Set and delete attr are considerably faster!

**Comment by cdgriffith** [comment]
Hey @jkylling if you could do me a favor and test the current development branch I have it in PR for 4.2.0 release now.

`pip install git+https://github.com/cdgriffith/Box.git@development`

**Comment by cdgriffith** [comment]
4.2.0 is now released, so going to close this issue hoping it is fixed, but if there are any issues let me know! 

Thanks for all the help!
