### ISSUE TITLE
default_box_attr does not accept values which evaluate to False

### ISSUE THREAD

**Issue by iordanivanov** [cdgriffith/Box#131]
https://github.com/cdgriffith/Box/blob/561548983c8956eac486c8cf99f5801e1155972a/box/box.py#L177
https://github.com/cdgriffith/Box/blob/561548983c8956eac486c8cf99f5801e1155972a/box/box.py#L200

Giving a default value such as None, False, 0, "" or an empty collection does not work, since they evaluate to False at the `or` operators in the referenced lines and Box reverts to `cls.__class__`.

Currently, this can be circumvented in the following way:
```python
from box import Box


class OtumeelFactory:
    def __init__(self, val):
        self.val = val

    def spawn(self):
        b = self.val

        class Otumeel:
            def __new__(self):
                return b

        return Otumeel


black_marsh = OtumeelFactory(0)
thief = black_marsh.spawn()

box = Box(default_box=True, default_box_attr=thief)
# It just works
print(box.t)


black_marsh = OtumeelFactory(None)
thief = black_marsh.spawn()

box = Box(default_box=True, default_box_attr=thief)
# 16 times the default values
print(box.t)


black_marsh = OtumeelFactory(False)
thief = black_marsh.spawn()

box = Box(default_box=True, default_box_attr=thief)
# See that False? You can return it
print(box.t)
```

**Comment by iordanivanov** [comment]
Ah, there is already an issue about this problem open. Sorry for the duplicate issue. I'll leave this one open if someone wants to use the workaround until the problem is fixed.

**Comment by iordanivanov** [comment]
Also, an easier workaround for `None` as the default value is to substitute it with `type(None)`

**Comment by cdgriffith** [comment]
Thanks for the report and the ideas! As this is a dup I am closing it in favor of https://github.com/cdgriffith/Box/issues/130 , please report anything else there.
