### ISSUE TITLE
to_json() creates str

### ISSUE THREAD

**Issue by staylorx** [cdgriffith/Box#138]
Given a JSON example (Python 3.7.4 for all):
```
json_string = """
{  "entity": "ENTITY" }
"""
entity = Box.from_json(json_string)
print(entity)
print(type(entity))
```

I get,
```
{'entity': 'ENTITY'}
<class 'box.box.Box'>
```

Doing the same thing with YAML, given,
```
yaml_string = """
entity: "ENTITY"
"""

entity_temp = Box.from_yaml(yaml_string)
entity = entity_temp.to_json()
print(entity)
print(type(entity))
```

I get,
```
{"entity": "ENTITY"}
<class 'str'>
```

In the first example I can use the `entity` variable directly with `requests.put(...,json=entity,...)`. The second one I have to json.loads()... which is pretty much why I was starting to use Box in the first place.

Your documentation is clear that to_json outputs as a string (or a filename).

Similar to json.load and json.loads, at some point maybe to_json() and to_jsons() might be useful?

Thanks for the useful work on this library. It's handy.

**Comment by cdgriffith** [comment]
I'm not sure I completely follow. In the second example you seem to be transforming the box to a JSON string unnecessarily? You could do the same thing as you did with the first example and use the box directly, if you are looking for a `dict` like object. 

```python
yaml_string = """
entity: "ENTITY"
"""

entity = Box.from_yaml(yaml_string)
print(entity)   # {'entity': 'ENTITY'}
print(type(entity)) # <class 'box.box.Box'>
```

**Comment by cdgriffith** [comment]
@staylorx were you able to figure it out?

**Comment by staylorx** [comment]
More or less. This can be closed. Thank you for looking into it.
________________________________

**Comment by cdgriffith** [comment]
Thanks for the reply. A little off topic, but one thing that you did make me think about is that to_json and the other converters can't take an open file handler like `json.load` can, and might be a nice addition.
