### ISSUE TITLE
Add multiline JSON support

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/Box#14]
Some odd people like to put multiple JSON objects into a file, one per line. Possibly make a 'multiline' kwarg for `to_json` under `BoxList` to accommodate?

**Comment by wbolster** [comment]
those are not weird but smart people. ;)

jsonlines.readthedocs.io and jsonlines.org

**Comment by cdgriffith** [comment]
Either way, at least I though of them ;-) 

Thanks for the references!

**Comment by cdgriffith** [comment]
Added in 3.1 https://github.com/cdgriffith/Box/commit/252e2f574213708cbbcd42bdec442434384127fe
