### ISSUE TITLE
Jupyter's autoreload fails when subclassing Box

### ISSUE THREAD

**Issue by tasercake** [cdgriffith/Box#146]
This is a little obscure and probably not that common of a use case, but I'd like to subclass `Box` to modify the `__str__` method.

I'm also using this in a Jupyter notebook, and for the sake of convenience I'd like to use the `autoreload` extension so I don't have to keep re-running my import statements after every change to external files.

Steps to reproduce:

- Create a python module where you subclass `Box`
```python
# sub.py
from box import Box
class Sub(Box):
    pass
```
- In a Jupyter notebook, load the `autoreload` extension with mode `2`
```
%load_ext autoreload
%autoreload 2
```
- In the notebook, import the new class and instantiate an object from it
```python
from sub import Sub
d = Sub()
```
- Re-save the python file containing the subclass definition (this notifies `autoreload` that something in the module has changed), then re-run the aforementioned notebook cell

This results in 
```
[autoreload of sub failed: Traceback (most recent call last):
  File "/opt/anaconda/miniconda3/envs/ai/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/opt/anaconda/miniconda3/envs/ai/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "/opt/anaconda/miniconda3/envs/ai/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/opt/anaconda/miniconda3/envs/ai/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 317, in update_class
    update_instances(old, new)
  File "/opt/anaconda/miniconda3/envs/ai/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 280, in update_instances
    ref.__class__ = new
  File "/opt/anaconda/miniconda3/envs/ai/lib/python3.7/site-packages/box/box.py", line 369, in __setattr__
    raise BoxKeyError(f'Key name "{key}" is protected')
box.exceptions.BoxKeyError: 'Key name "__class__" is protected'
]
```

I've tried and failed to find the cause of the error (apart from the fact that `__class__` is part of `Box._protected_keys`)

**Comment by tasercake** [comment]
On further debugging, it looks like subclassing isn't necessary to reproduce this issue.

Simply creating a `Box` in an Ipython notebook that has the `autoreload` extension enabled and re-saving the `box.py` module in `site-packages` (or wherever you have it installed)  triggers the problem.

**Comment by cdgriffith** [comment]
Yeah, I do by default protect all built in `dict` and other attributes to make it less problematic from people accidentally overwriting an important function. 

https://github.com/cdgriffith/Box/blob/master/box/box.py#L93

However, it's probably better to reduce this to non magic methods only, as anyone trying to overwrite a dunder method should know what they are doing.

**Comment by tasercake** [comment]
That's more or less what I ended up doing.

```python
class Box(dict):
    _autoreload_compat_keys = [
        "__class__",
    ]  # Hack to make this class work with Ipython's autoreload

    def __setattr__(self, key, value):
        ...
        if key in self._protected_keys:
            if key in in self._autoreload_compat_keys:
                object.__setattr__(self, key, value)
            else:
                raise BoxKeyError(f'Key name "{key}" is protected')
        ...
```

It's ugly, but it works well enough for what I need

**Comment by cdgriffith** [comment]
Addressing this issue in Box 5.0 https://github.com/cdgriffith/Box/pull/145 
There is also an edge case with the `to_dict` being called for `repr` in certain circumstances of ipython with autoreload enabled that is fixed as well.
