### ISSUE TITLE
Access sub dictionary keys with box.get('key.subkey.subsubkey')

### ISSUE THREAD

**Issue by scott-createplay** [cdgriffith/Box#161]
Love the library. I was looking into subclassing box.Box to get this working, but wanted to make sure it wasn't already present in the library.

Imagine a situation like this:

`my_data = box.Box({ 'level_1': {level_2:{level_3: my_value}}})`

Currently to get to the level_3, I would need to do:

`eval('my_data.level_1.leve_2.level_3)`

Ideally, I would want to do:

`my_val = my_data.get('level_1.level_2.level_3')`

Of course I could just do:

`my_val = my_data.level_1.level_2.level_3`

However, I am encoding my dot access in config files as strings, so this would cause a syntax error as 'level_1' is not a variable.

is there a way to accomplish this with the current implementation of python-box?

Thanks in advance

**Comment by cdgriffith** [comment]
Actually there is almost exactly what you are looking for already, if you enable `box_dots=True` you can access variables via dot notation as dict keys. 

```
my_data = Box({ 'level_1': {'level_2': {'level_3': 'my_value'}}}, box_dots=True)

my_val = my_data['level_1.level_2.level_3']

print(my_val)
# my_value
```

However, you did just point out something I forgot to add was the ability to do that via the `get` method as well, so I am keeping this open to track that effort.

**Comment by scott-createplay** [comment]
Hey Chris,

Thanks for the heads up. This is great. One other aspect, that is related is the "in" check. IE-

`myBox = box.Box({"this": {"is": {"my": "box"}}})`

I would want to be able to check for the key's existence in the same way:

`"this.is.my" in myBox`
Currently returns False, but it would be nice to be able to check for nested keys.

Any thoughts / recommendations are welcomed!
Thanks
-s

**Comment by cdgriffith** [comment]
Adding these features in 6.0, currently have a release candidate that can be installed and tested with:

```
pip install python-box==6.0.0rc2
```

6.0 is ushering in Cython speedups on supported platforms, so please let me know if you run into any issues!

**Comment by cdgriffith** [comment]
[Box 6](https://github.com/cdgriffith/Box/releases/tag/6.0.0) has been released with this added, thanks for opening the issue!
