### ISSUE TITLE
Pylance / VSCode compatibility 

### ISSUE THREAD

**Issue by ernesto** [cdgriffith/Box#163]
First, amazing work, your library rocks!
How to get Box working with Pylance or other VSCode Python Server?

![Screen Shot 2020-08-04 at 15 28 35](https://user-images.githubusercontent.com/210907/89330974-63a5b080-d667-11ea-8413-42d46b5e1c31.png)

![Screen Shot 2020-08-04 at 15 28 58](https://user-images.githubusercontent.com/210907/89330981-686a6480-d667-11ea-8e20-bd24673c8da2.png)

**Comment by cdgriffith** [comment]
Hi @ernesto  thanks for reportiing this, I have not used VSCode before, so I will have to do some digging into this. It's odd to be it's reporting it incorrectly as type "BoxList" and not "Box" so I am unsure how it's inspection is making that jump.

**Comment by trallnag** [comment]
It works for me with the Microsoft Python Language Server

**Comment by macintacos** [comment]
Workaround to get Pylance to stop complaining is to just add `# type: ignore` at the end of the line. FWIW, I don't necessarily think that this is an issue with Box, but rather an issue with Pylance's understanding of how Box works (it has no way to understand the dot-syntax I think).

If there isn't a corresponding issue open in Pylance, I'll go ahead and open one and link it here.

**Comment by macintacos** [comment]
Another example is in #197 (closed that out after I realized that it was just another iteration of this issue).

**Comment by macintacos** [comment]
As of the most recent version of VSCode, the errors that get presented when you set `"python.analysis.typeCheckingMode": "basic"` are getting more frustrating to deal with, apparently. [One of the maintainers there helpfully pointed](https://github.com/microsoft/pylance-release/issues/2528#issuecomment-1086323304) to this document that can be used to help annotate modules properly so that VSCode can more accurately type things in the editor: https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md

**Comment by cdgriffith** [comment]
I was very confused as it is mostly typed https://github.com/cdgriffith/Box/blob/master/box/box.pyi  however I downloaded `whl` from pypi to check, and see those files aren't being stored, and are missing from the manifest 🤦 

However even with those files, I don't know how much it will help, as it will still be typed to `Any` for most things as the getters can return most anything that can be put in a `dict`.

**Comment by cdgriffith** [comment]
6.0.2 fixes the typed stuff not being added to the whl. Can anyone check to see if that helps or hurts VSCode? https://github.com/cdgriffith/Box/releases/tag/6.0.2

**Comment by macintacos** [comment]
I've been unable to test this, but one of my colleagues managed to test this and indeed the issue does go away for us in 6.0.2. Thanks @cdgriffith!
