### ISSUE TITLE
No Output in Default Sublime Build Window

### ISSUE THREAD

**Issue by chavenor** [cdgriffith/Box#17]
OS:
 Windows 7 
 Sublime 2.0 

Works in terminal.   
Low priority. 
See gif.  When running under default python build env runs without error but not of the links show up.

```python
from box import Box

class Job(object):
	"""Configure the job object via runner."""
	def __init__(self, **kwargs):
		self.job = Box(kwargs)


job = {
	'uuid': None,
	'started' : None,
	'force_stop': None,
	'created_by ': None,
	'created_date': None,
	'status': 'Building',
	'last_saved': None,
	'debug': True,
	'human_name': "Refusa Record Extractor - Restaurant SIC Codes",
	'record_tag': 'refusa-restaurant',
	'error_count': 0,
	'last_error': None,
	'extraction_last_event': None,
	'extraction_average_time': 0,
	'extraction_completion_time': 0, #Seconds
	'extraction_total_records': 0,
	'extraction_duplicate_records': None,
	'search_total_records_found': None,
	'page_current' : None,
	'page_last' : None,
	'driver' : None,
	'pending_tasks':[],
	'task': {
		'inputs': {
			'load_page': { 'url': "https://google.com" },
			'screenshot_as_base64' : { 'file_name' : None, }
		}, 
		'outputs': {
			'generate_refind_key' : None,
			'add_tag_record': None,		
			'save_record': None,
			'refind_record': None,
		}
	},
	'completed_tasks':[],
}

tjob = Job(**job)

tjob.job.status
tjob.job.error_count
tjob.job.task.inputs.load_page.url
tjob.job.human_name
tjob.job.task.inputs.screenshot_as_base64.file_name

```

![no-output](https://cloud.githubusercontent.com/assets/1850981/25629890/ce7ead9e-2f30-11e7-9729-c306a65561b7.gif)

**Comment by cdgriffith** [comment]
I think this is expected behavior. This is the same as just doing: 

`job["status"] `

So when in a console, it will default show the output if there is no action being taken. but in a script to get it to go to `stdout` you would have to do:
`
print(job["status"])
# or 
print(tjob.job.status)
`
Is that what you mean / think is going on? 

Thanks for the `gif` btw, would have been very hard to wrap my head around without it 👍

**Comment by chavenor** [comment]
Yeah when I add print we're all good.   I can see the keys value.   Closing this.   I'll make the gifs smaller in the future.  

Thanks! 

Casey
