### ISSUE TITLE
Have frozen boxes throw an error for mutating dictionary methods

### ISSUE THREAD

**Issue by vamega** [cdgriffith/Box#171]
I think that frozen boxes should throw an exception when method like `pop`, `popitem` and `clear` are called.
This will strengthen the contract of the hash code method, and make it safer to store frozen boxes as keys.

If you agree then I'd be happy to send a PR.

**Comment by cdgriffith** [comment]
Yup, that was a total miss, please feel free to send over a PR!

**Comment by cdgriffith** [comment]
fixed in https://github.com/cdgriffith/Box/releases/tag/5.3.0
