### ISSUE TITLE
Recast exceptions are masked

### ISSUE THREAD

**Issue by JacobHayes** [cdgriffith/Box#179]
The `__recast` (and other) error handling raise errors with `from None`:

https://github.com/cdgriffith/Box/blob/4a505124686c1f0b79ea84bb292aec331ee70f51/box/box.py#L420

This causes the underlying exception to be completely hidden. It would be helpful to keep the original error/stacktrace, for example when using https://github.com/cdgriffith/Box/pull/178 to validate data.

What does the `from None` do here (does it prevent deeply nested stacktraces in certain cases)? Would it be possible to remove that or possibly replace `from None` with:
```python
                from_ = e.__cause__ if isinstance(e, BoxValueError) else e
                raise BoxValueError(f'Cannot convert {value} to {recast}') from from_
```
to keep only the inner and outermost exceptions? I'm happy to open a PR up if this makes sense to you. Would it make sense to do similar for all other `from None`?

**Comment by cdgriffith** [comment]
You are correct! I was trying to reduce some horribly long stack traces in some instances. 

I would love a PR for that, thanks for your hard work and suggestions!

I haven't looked into it at all, but would the check need to make sure `e.__cause__` exists or does the Exception class always have that? (It's fine if it's None for some reason, just want to make sure we never get an attribute error)

**Comment by JacobHayes** [comment]
> does the Exception class always have that?

Good question, [PEP 3134](https://www.python.org/dev/peps/pep-3134/#explicit-exception-chaining) says yes and some anecdotal testing seems to look good:
```python
>>> try:
...     raise ValueError  # Think this is allowed but deprecated?
... except ValueError as e:
...     print(e.__cause__)
...
None
>>> err = None
>>> try:
...     raise ValueError("Base error")
... except ValueError as e:
...     err = e
...     print(e.__cause__)
...
None
>>> try:
...     raise ValueError() from err
... except ValueError as e:
...     print(e.__cause__)
...
Base error
```
I'll see what I can do!

**Comment by JacobHayes** [comment]
https://github.com/cdgriffith/Box/pull/180 feels like a good improvement, but on further thought, what do you think about removing this error handling entirely (only for `__recast`):

https://github.com/cdgriffith/Box/blob/4a505124686c1f0b79ea84bb292aec331ee70f51/box/box.py#L419-L420
?

Seems like it could be a breaking change (message change or users might be catching `BoxValueError` over `ValueError`), but I think it'd make my use a little bit nicer (my validation/parsing error message would be shown directly). FWIW, removing it didn't break any of the tests (except for my newly added one in #180 that was looking in `.__cause__` 😁).

**Comment by JacobHayes** [comment]
Closing after #180's merge and decision in #188.
