### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by csurfer** [cdgriffith/Box#19]
Oversimplifying the whole library would imply `JSON -> PyDict with dot notation` is what is being done here. As parsing JSON can be very slow, I am very much interested in some perf numbers as to how it scales. Can you please add these metrics in README ?

**Comment by cdgriffith** [comment]
Just as a heads up, just posted about the current revisions speed vs dict and other libraries: 

http://www.codecalamity.com/python-box-3-the-reddit-release/#speed-and-memory-usage

As it seems to be a commonly asked for detail, I agree could be important enough to add to the readme

**Comment by csurfer** [comment]
@cdgriffith : Nice work!
