### ISSUE TITLE
Protecting attributes and default_box cause hasattr() issues.

### ISSUE THREAD

**Issue by Rexbard** [cdgriffith/Box#193]
Consider the following code:

```python
bx = Box(default_box=True)
if hasattr(bx, "_noop_attr"):
    delattr(bx, "_noop_attr")
print(bx)
```

The expectation is that `{}` is printed as the contents of the Box. However, a *BoxKeyError* is thrown, instead. The reason is that the `hasattr()` call returns True, but the attribute does not exist, so `delattr()` raises the exception.

Here's the details:

1) `hasattr()` uses `Box.__getattr__()`, which after a few checks executes the following code:

```python
if self._box_config["default_box"]:
    return self.__get_default(item, attr=True)
```

2) The called `Box.__get_default()` method eventually reaches the following code.

```python
if not attr or (not item.startswith("_") and not item.endswith("_")):
    super().__setitem__(item, value)
```

Since the conditional in (2) is False due to item starting with an underscore, '_noop_attr', it is *not* added to the box. However, the code in (1) still returns the new, default box.

This results in the `hasattr()` conditional evaluating true, which tries to execute `delattr()`. Since the item/value pair was not added, a `BoxKeyError` is raised.

There are a couple of fixes required. From cdgriffith's comment in https://github.com/cdgriffith/Box/issues/155, it looks like the conditional in `Box.__get_default()` should be corrected to one of the following.
```python
if not attr or not (item.startswith("_") and item.endswith("_")):
if not attr or not item.startswith("_") or not item.endswith("_"):
```

In addition, if this underscore protection should remain, preventing creation of certain keys, then the same conditional needs to be in the `__getattr__()` call to prevent returning key values for keys that do not exist.

Based on the behavior when handling key="_box_config" in `Box.__get_item__()`, I'd recommend raising a similar BoxKeyError in `__getattr__()`.

```python
if self._box_config["default_box"]:
    if item.startswith("_") and item.endswith("_"):
        raise BoxKeyError(f"{item}: internal methods and restricted options are never defaulted")
    return self.__get_default(item, attr=True)
 ```

The associated test would also be changed:

```python
    def test_default_box_restricted_calls(self):
        a = Box(default_box=True)
        with pytest.raises(BoxKeyError):
            a._test_thing_
        assert len(list(a.keys())) == 0

        # Based on argparse.parse_args internal behavior, the following
        # creates the attribute in hasattr due to default_box=True, then
        # deletes it in delattr.
        if hasattr(a, "_unrecognized_args"):
            delattr(a, "_unrecognized_args")

        a._allowed_prefix
        a.allowed_postfix_
        assert len(list(a.keys())) == 2
```
This error was found when attempting to use Box with argparser's `parse_args()`. parse_args does the `hasattr()/delattr()` logic with the key '_unrecognized_args', which causes the BoxKeyError.

**Comment by cdgriffith** [comment]
Thank you for this great write up and details. This has been addressed in https://github.com/cdgriffith/Box/releases/tag/5.4.0
