### ISSUE TITLE
[Feature Request] return None if a key doesn't exist

### ISSUE THREAD

**Issue by ow0x** [cdgriffith/Box#203]
Hi,

Thank you very much for making this nifty useful tool. I recently discovered this and started using this in my small project and it has proved to be time saver in some areas. ❤️

One possible enhancement I would like to request is an option to make it gracefully return None (or even better, to return a preset default value instead, e.g. "foo") if a key we are trying to access with dot notation doesn't exist in a dictionary instead of raising KeyError or other relevant errors. This could be really useful and time saving in some scenarios in my opinion instead of trying to catch the error with try-except.

Maybe something like this for a rough example:

```py
from box import Box

data = {"a": {"b": {"d": "e"}}}
new_data = Box(data)

new_data.a.b.c
# None

foo = Box(data, custom_default="foo")
foo.a.b.c
# "foo"
```

**Comment by cdgriffith** [comment]
I got ya fam: https://github.com/cdgriffith/Box/wiki/Types-of-Boxes#default-box

**Comment by ow0x** [comment]
oh wow, not sure how I missed it. 😂
Sorry for any inconvenience, I'll clock this, thank you again!
