### ISSUE TITLE
Aliased keys can be overwritten without warning

### ISSUE THREAD

**Issue by wimglenn** [cdgriffith/Box#21]
Box doesn't warn when data is shadowed 

```
>>> d = {'to': 'chris@cdgriffith.com', 'from': 'hey@wimglenn.com', 'subject': 'bugs'}
>>> b = Box(d)
>>> b.to
'chris@cdgriffith.com'
>>> b.from
SyntaxError: invalid syntax
>>> b.xfrom
'hey@wimglenn.com'
>>> Box({'to': 'chris', 'from': 'wim', 'subject': 'bugs', 'xfrom': 'wat'}).xfrom
'wat'

```

**Comment by cdgriffith** [comment]
I am trying to think how to best approach this. Best idea I have as of now is how the build-in encoding gives different options for `errors`, and have something like `ignore` (what it does not), `error` (raise exception as soon as it detects clashing keys) or `warn` (would use built in warning module to print warning).

**Comment by wimglenn** [comment]
Yes.  My recommendation is to raise as default behavior, with an "opt-in" kwarg specified at box creation of you want it to 'warn' or 'squash'.  You may also want to handle dicts with __dunder__ keys carefully.

**Comment by cdgriffith** [comment]
Adding `box_duplicates` option that accepts `"ignore" | "error" | "warn"`  in 3.1

```python
a = Box({'a': 3}, box_duplicates="error")
a['!a'] = 4 

BoxError: Duplicate conversion attributes exist: set(['!a(a)'])
```

Setting to "ignore" by default to match 3.0 behavior. 

Right now box doesn't allow overrides of magic methods, however they will work fine in the dictionary object so that shouldn't be an issue, but thank you for the warning 😄 

``` python
a['__dir__'] = 4 
a
# <Box: {'a': 3, '__dir__': 4}>
a.__dir__
# <bound method Box.__dir__ of <Box: {'a': 3, '__dir__': 4}>>
a.__dir__()
# ['from_json', '__str__', ...
a['__gt__'] = 4
a.__gt__
# <method-wrapper '__gt__' of Box object at 0x7fbe4727d990>
```

**Comment by cdgriffith** [comment]
Added in 3.1 https://github.com/cdgriffith/Box/commit/252e2f574213708cbbcd42bdec442434384127fe
