### ISSUE TITLE
ModuleNotFoundError: No module named 'box'

### ISSUE THREAD

**Issue by kwalkerk** [cdgriffith/Box#212]
I get the following error when I have this line in my code:
          from box import Box

ModuleNotFoundError: No module named 'box'

I've installed on RasPi Zero using pip3 install box.  Also tried the regular pip install box.

Am running Python 3 3.7.3

Am I missing something obvious?

Thanks,
Ken

**Comment by cdgriffith** [comment]
`pip install python-box` 

`box` is reserved or something and couldn't get that name on `pypi`, so have to type out `python-box` for the install.

**Comment by kwalkerk** [comment]
I did that. No joy. Same error message

**Comment by cdgriffith** [comment]
When running python, are you calling `python3` and did `pip3 install python-box`?

**Comment by kwalkerk** [comment]
Yes to both

**Comment by cdgriffith** [comment]
Can you paste the full output of: 

```
pip3 install --upgrade python-box
python3 -c "import box" 
```

**Comment by kwalkerk** [comment]
Here’s the output:

$ pip3 install --upgrade python-box
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: python-box in ./.local/lib/python3.7/site-packages (5.4.1)
$ python3 -c "import box"
$ 

This lead me to the solution.  The program I run must be run under “sudo”.  When I installed the package I did not use “sudo pip3 install —upgrade python-box”.  Once I installed it that way, all was well.

Sorry to have wasted your time with my ignorance.  

Thanks for your quick help!

**Comment by cdgriffith** [comment]
No problem at all, glad it's working for you now!

**Comment by d1c2s3** [comment]
from utils.prior_box import PriorBox
ModuleNotFoundError: No module named 'utils.prior_box'
Can you help me figure it out, thanks！

**Comment by cdgriffith** [comment]
@d1c2s3 that is some other library, not this Box
