### ISSUE TITLE
Version mismatch between setup.py and tag

### ISSUE THREAD

**Issue by mgorny** [cdgriffith/Box#233]
The most recent release seems to be meant as version 6.1.0 but the git tag is 6.10.0. Could you fix, please?

**Comment by cdgriffith** [comment]
Crap, thanks for the heads up! Fixing tag.

**Comment by mgorny** [comment]
Thank you!

**Comment by cdgriffith** [comment]
Old tag deleted and replaced and version in releases updated. 

Not going to force push to rewrite history for the commit itself, so that will be a nice long running reminder for me 🙄
