### ISSUE TITLE
Using help (`?`) with `default_box=True` unintentionally adds a key

### ISSUE THREAD

**Issue by nishikantparmariam** [cdgriffith/Box#236]
Box is really useful when accessing non-existing keys/attributes and assigning new keys on them e.g. `box.foo.bar.baz = 1`. 

Noting down here an issue I have found. When IPython's help using `?` is called it adds a key `getdoc` in Box object.

#### Version
python-box v6.1.0

#### Reproducer
![box-repro](https://user-images.githubusercontent.com/7736252/208438269-e4381372-fc94-4ffa-91b4-886cd7428fb6.png)

#### Cause
This seems expected and is a side-effect of [this](https://github.com/ipython/ipython/blob/ae0dfcd9d4fb221f0278f07b022f9837b0e51e67/IPython/core/oinspect.py#L124) line in IPython which tries a find a custom method `getdoc()` to get docstring for an object. 

Is there a workaround here?

**Comment by nishikantparmariam** [comment]
Ok, I've found a workaround for now - 
```python
from box import Box

class MyBox(Box):
    _protected_keys = dir(Box) + ['getdoc']
    def getdoc(self):
        return Box.__doc__
```

**Comment by cdgriffith** [comment]
Hopefully fixing both `getdoc` and `shape` if we detect we are in an ipython console 

Adding this feature in Box 7! Please test and give feedback if possible `pip install python-box[all]~=7.0.0rc0`

**Comment by cdgriffith** [comment]
Added in [7.0.0](https://github.com/cdgriffith/Box/releases/tag/7.0.0)
