### ISSUE TITLE
Switch to poetry-core

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/Box#246]
https://github.com/cdgriffith/Box/pull/244 brought up by Michał Górny @mgorny 

https://python-poetry.org/docs/pyproject/#poetry-and-pep-517

**Comment by cdgriffith** [comment]
killing off poetry for next version

**Comment by mgorny** [comment]
For the record, you can some of the same "feeling" (at least config-side) with [modern setuptools pyproject.toml configs](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html).
