### ISSUE TITLE
Missing python-box 7.0.0 arm64 wheels

### ISSUE THREAD

**Issue by tekumara** [cdgriffith/Box#249]
For macos and linux on my m1 arm64 machine it downloads the source and tries to build it.

**Comment by cdgriffith** [comment]
Github actions do not support wheels for arm64, however previously there was a generic wheel upload that didn't have Cython support and would run without trying to build, looks like it was missing in 7.0.0. Should be fixed in 7.0.1, if it tries to build still for you please let me know!
