### ISSUE TITLE
path as string

### ISSUE THREAD

**Issue by sgordon46** [cdgriffith/Box#254]
In trying to use the syntax from  #57 

I have these two examples

```
print(boxed_items.credential.type)
print(boxed_items['credential.type'])
```

the first one will print the value just fine, but the second with throw this error

```
Traceback (most recent call last):
  File "box/box.py", line 587, in box.box.Box.__getitem__
KeyError: 'credential.type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sgordon/repos/PANW/agentless-bulk-operation/cloud-account-status.py", line 128, in <module>
    print(boxed_items['credential.type'])
          ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'credential.type'"

```
Suggestion?

I'm passing in the path via a cli argument, so it will be a string that I need to reference.

**Comment by cdgriffith** [comment]
Oh box creation, did you set `box_dots=True` ?

documentation https://github.com/cdgriffith/Box/wiki/Types-of-Boxes#box-dots

**Comment by sgordon46** [comment]
I did not, thanks for pointing that out. I knew I was missing something easy. 

I'll test and close this out if so.
