### ISSUE TITLE
Figure out best way to deal with circular references

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/Box#26]
As discovered with https://github.com/cdgriffith/Box/issues/20

Issue can be duplicated with:

```python
troll_dict = {}
troll_dict ['e'] = {'g': troll_dict}

bx = Box(troll_dict)
bx.e.g
<Box: {'e': {'g': {'e': {'g': {'e': {'g': {'e': {'g': {'e': {'g': {'e': ..................
```

Also would include way to detect and raise custom `BoxError` instead of related recursive built in error for functions like `box_it_up`. 

Other libraries such as `addict` and `DotMap` cannot handle even first level circular references, so may not be an easy or worthwhile thing to address.  

Only current thought on how to address it would be to keep list of references to original objects that were converted, and upon creation of sub-boxes check all other previously generated ones to see if any have that link already and re-reference the newly created sub-box. The issue is that this would be very memory and process heavy for a rare issue check.

**Comment by dhilipsiva** [comment]
@cdgriffith How about passing in a flag to force validation before even calling `box_it_up`. That way, old behavior would not change and and people can invoke validation as and when required. Have done a version of circular dependency check before: https://gist.github.com/dhilipsiva/ff61a8e4a5f962590c86b3beb02b24e6#file-spreadsheet-py-L79

**Comment by cdgriffith** [comment]
With the new version 4 release, circular references will be unsupported, like in addict or DotMap, as that is non-standard behavior.
