### ISSUE TITLE
infinite recursive when dictionary has array of dictionary refer to the parent.

### ISSUE THREAD

**Issue by eric-zhu-2019** [cdgriffith/Box#278]
for example:
```
>>> import box
>>> a={'a': 1}
>>> a['b'] = [{'parent': a}]
>>> box.Box(a)
Traceback (most recent call last):
...
RecursionError: maximum recursion depth exceeded in __subclasscheck__

```
any idea? how to implement the data structure like this?
Thanks!

**Comment by cdgriffith** [comment]
Hi @eric-zhu-2019 as of Box 7.1 we do not support circular references inside of lists https://github.com/cdgriffith/Box/wiki/Major-Version-Breaking-Changes
