### ISSUE TITLE
how to achieve the incoming path parameters,Thanks?

### ISSUE THREAD

**Issue by xie0723** [cdgriffith/Box#32]
`from box import Box`

`bx = Box({'a': {'b': {'c': 1}}})`

`print(bx.a.b.c)` #out 1

------------------------
but like this :

`path_ = 'a.b.c'`

`print(bx.path_) `  # error

thanks

**Comment by cdgriffith** [comment]
I do not personally know of any Python built in ways to achieve that behavior . The best option I would guess off the top of my head is to convert it into a list of keys `'a.b.c'.split('.')` -> `['a', 'b', 'c']`   , then [traverse the directory](http://stackoverflow.com/questions/14692690/access-nested-dictionary-items-via-a-list-of-keys) that way.

**Comment by xie0723** [comment]
awesome, Thank you very much！
