### ISSUE TITLE
Look into auto conversion of keys to proper attributes

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/Box#4]
It would be beneficial to be able to access things that have spaces in them via dot notation, by assuming that spaces are underscores.  

```
b = Box({"my dict": 1})
b.my_dict
```

This will require changes in both get and `dir`. 

Also consider adding auto snake_case to stuff that is camelCase, and potentially lower case for anything as well.

**Comment by luizpericolo** [comment]
I am interested in looking into this. After I head about the projects over at python bytes I immediately thought of this feature. Checked the issues only to see it already documented here.

**Comment by cdgriffith** [comment]
Hey @luizpericolo, thanks for making me aware this made it onto Python Bytes, I had no idea! 

Those features are complete and in https://github.com/cdgriffith/Box/tree/development , most of the dev work is done for 3.x (hopefully), just needs a lot more testing and to update the documentation before release.

**Comment by cdgriffith** [comment]
3.0 added this feature https://github.com/cdgriffith/Box/commit/6d90e4213365b66585de60676d317a80fe2607bc
