### ISSUE TITLE
Feature Request: LayeredBox

### ISSUE THREAD

**Issue by epruesse** [cdgriffith/Box#49]
When using `Box` to represent a configuration hierarchy, it would be great to be able to have a `LayeredBox` virtually merging multiple `Box`es in layers. That way, `Box`es containing content from say a system wide, user specific and directory specific configuration could be combined while retaining the ability to write back changes using a round-trip yaml parser to preserve formatting and comments in the config provided by the user.

The `LayeredBox` would probably require some flags defining the way merging is done recursively. Should dictionaries at all levels be combined, or should they be overwritten? Should lists be overwritten or merged by appending? Typically, you'd want dictionaries to be merged and lists to be overwritten I think. It's a semantic decision though.

**Comment by omry** [comment]
Please take a look at [OmegaConf](https://github.com/omry/omegaconf) which this natively, and while you are at it take a look at [Hydra](https://hydra.cc) which probably solve a bunch of other problems you are having.

**Comment by cdgriffith** [comment]
Hi @epruesse, after thinking about this for a while, I do think that it would be best to either turn to one of the alternatives @omry mentioned or should be it's own project, as it has a lot going on itself.

**Comment by epruesse** [comment]
@cdgriffith Thanks - I will do that. Perhaps I can toss the (fragile) code I hacked up for myself in the mean time...
