### ISSUE TITLE
hierarchical path as string

### ISSUE THREAD

**Issue by ipcoder** [cdgriffith/Box#57]
Would you consider to support dotted string as a access key to sub boxes:
```python
b=Box(dotted=True)

b.c.d.e = 10
b['c.d.e'] == b.c.d.e
```
That is, to have an equivalence between those two notations.
If positive, then also to support some corresponding functions for traversing (for example):
```python
b = Box(dotted=True)
b.c = dict(e=1, f=2)
b.a = dict(b=3, c=4)
[*Box.keys(dotted=True)]
# ['c.d.e', 'c.d.f', 'a.b', 'a.c']
```
Thanks!

**Comment by cdgriffith** [comment]
I do think that is an interesting idea and merits looking into adding. 

I will have to think about it some, and how it will interact with the other box types. Questions for me to answer while developing this: 

- How will it work with conversion box, will it actually accept dot strings with spaces in and fix them? 
- Will it work with camel_killer_box, or does dotted simply have to be exact?
- What's the most efficient way to implement this to cause little to no overhead when not using this feature? 

Thanks for the great idea! 👍

**Comment by ipcoder** [comment]
I had only a quick look at the code, so probably I can miss some details, but it seems that it may be possible to think about that as a kind of a `wrapping` interface.

For example, in the case of  `__getattr__` :
- first (overhead related) check something like that:
```python
if self._box_config['frozen_box'] and '.' in item:
   # Only then activate the "dotted machinery".
   # If dotted setting is OFF the overhead will be this check:
   # self._box_config['dotted'] ==  False   
```
- and then (considering the camel_killer_box and conversion and actually all similar questions),   
split the `item` by dots and just chain call `__getattr__` with each of them,
leaving all the existing logic to deal with whatever will be found in those keys sub-strings.

Not sure how that is helpful, but it may be good to treat this dotted string just as another syntactic option which is otherwise equivalent to the regular behaviour.

**Comment by cdgriffith** [comment]
Just wanted to give an update that I do have the start of this feature in the 4.0 branch. (And no parameters required!) 

```
>>> a = Box(test={'a': {'c': 'd'}})
>>> a['test.a.c']
'd'
````

I haven't wrapped my brain around how best to traverse all the keys yet but I still also like having that option.

**Comment by cdgriffith** [comment]
Added in 4.0
