### ISSUE TITLE
Treat None values as unexisting keys for default_box

### ISSUE THREAD

**Issue by eMerzh** [cdgriffith/Box#59]
Hi, 

thanks a lot for your project, it's currently helping me a lot :)
one feature i missed is the ability to treat None values as if there was no key defined.

like in this example.

```python
b=Box({'brol': None}, default_box=True)
b.brol.truc
```
gives 
>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>AttributeError: 'NoneType' object has no attribute 'truc'

but this works as exepected
```python 
b=Box({}, default_box=True)
b.brol.truc
```

many many thanks 👍

**Comment by cdgriffith** [comment]
Hi @eMerzh , sorry for delay getting back. That could be an interesting feature to add, I will look into the effort for it when I get a chance (feel free to put in a PR as well.)  

 I have a few major life events happening / coming up, so I won't be available to contribute a good amount of time until after Thanksgiving or so as a forewarning.

**Comment by haruntuncay** [comment]
Hello @cdgriffith, if you are open to contributions, can I submit a PR for this issue ?

**Comment by cdgriffith** [comment]
Hi @haruntuncay I am always open to ideas and improvements! 

For this specifically as it changes current behavior it will need to target next major release, so if you do create it please do it off of the 4.0 branch. Thanks!

**Comment by haruntuncay** [comment]
@cdgriffith , I was going to give this issue a shot today, and wanted to ask for your opinion on whether this behavior should be configurable or not when a `default_box` is used ? For example, a config option might be:
`b = Box({'brol': None}, default_box=True, ignore_none_values=True)` , or it could just be as if that key never existed. Which do you think is more appropriate ?

**Comment by cdgriffith** [comment]
@haruntuncay  I think I like the idea of making this new feature the default behavior, but do have an option to opt out of it as there may be cases it to be compatible with the previous behavior. So maybe `default_box_none_transform=True` or something?

**Comment by haruntuncay** [comment]
Okay, I will update the PR accordingly. Are we set on `default_box_none_transform` as the name of the config option ?

**Comment by cdgriffith** [comment]
Added in 4.0
