### ISSUE TITLE
Box __hash__ does not adhere to the specification

### ISSUE THREAD

**Issue by cebaa** [cdgriffith/Box#60]
Per [Python docs](https://docs.python.org/3/reference/datamodel.html#object.__hash__), `__hash__` should have this property:

> The only required property is that objects which compare equal have the same hash value;

However:

```
def f():
  return Box(data={'Python': 'Rocks', 'inferior': ['java', 'cobol']}, frozen_box=True)

b1 = f()
b2 = f()
print(b1 == b2)
print(hash(b1), hash(b2))
print(set([b1, b2]))
```

yields:

```
True
-7253217714821940563 1337995706200090896
{<Box: {'data': {'Python': 'Rocks', 'inferior': ('java', 'cobol')}}>, <Box: {'data': {'Python': 'Rocks', 'inferior': ('java', 'cobol')}}>}
```

This also makes is unusable for using in `set`s, as seen in the above message.

The reason for this looks to be due to [\_\_hash__](https://github.com/cdgriffith/Box/blob/ae49ac284e993aae9f195b1e6a10029f63e7238e/box.py#L349) having a random `uuid4` included in the calculation:

```
                hashing = hash(uuid4().hex)
```

Is there a reason for this line?

**Comment by cdgriffith** [comment]
Good catch. I honestly can't remember why it was done that way, but does need to be updated. 

Off the top of my head, one way to achieve this would be to make Frozen boxes ordered as well, JSON it into a string, and run a cryptographic hash on it.

**Comment by cdgriffith** [comment]
You are correct on both counts! I have just pushed a fix for it to dev branch for tonight and added tests. Also added it to BoxList as now that supports freezing. 

https://github.com/cdgriffith/Box/commit/c0d2bf79722fe957cb25ef90a2095f0fe706ee22

**Comment by cebaa** [comment]
Great, thanks @cdgriffith!

**Comment by cdgriffith** [comment]
Fixed in https://github.com/cdgriffith/Box/releases/tag/3.2.2
