### ISSUE TITLE
py3.7 collections deprecation warning

### ISSUE THREAD

**Issue by deluxghost** [cdgriffith/Box#61]
https://github.com/cdgriffith/Box/blob/ae49ac284e993aae9f195b1e6a10029f63e7238e/box.py#L450

```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    elif isinstance(default_value, collections.Callable):
```

**Comment by cdgriffith** [comment]
Fix is currently in dev https://github.com/cdgriffith/Box/commit/59f18bd03afed9d6dd5e6fa94c157e69843830c5

**Comment by cdgriffith** [comment]
Fixed in https://github.com/cdgriffith/Box/releases/tag/3.2.2
