### ISSUE TITLE
Feature: Default box that doesn't raise key errors

### ISSUE THREAD

**Issue by Patrock** [cdgriffith/Box#67]
Hello,

Box is a nice little Dictionary Helper hich is working just fine most of the time. Currently i'm seeing a problem with the pop-method... When popping a non-exitent key with default_box=True i get a KeyError:

File "/mnt/d/projekte/python/envs/depmgmt/bin/box.py", line 592, in pop
    del self[key]
  File "/mnt/d/projekte/python/envs/depmgmt/bin/box.py", line 560, in __delitem__
    super(Box, self).__delitem__(key)

Is this working as intended ? I would expect to get the given default value when the key is not existant ?

Thank you...

**Comment by cdgriffith** [comment]
Hi @Patrock 

This is by design, to stay close to spec with the builtin `defaultdict` from [`collections` ](https://docs.python.org/3.7/library/collections.html#defaultdict-objects)

```
>>> from collections import defaultdict
>>> my_dict = defaultdict(int)
>>> my_dict['key1']
0

>>> my_dict
defaultdict(<class 'int'>, {'key1': 0})

>>> my_dict.pop('key2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'key2'
```

However I will leave this open for now to consider it as a feature request.

**Comment by Patrock** [comment]
Okay... thank you.

But isnt it ok to use pop with a default value if key isnt present?

dictionary.pop(key[, default])

________________________________
Von: Chris Griffith <notifications@github.com>
Gesendet: Freitag, 14. Dezember 2018 16:36:14
An: cdgriffith/Box
Cc: Pogscheba, Patrick; Mention
Betreff: Re: [cdgriffith/Box] Problems with pop (#67)


Hi @Patrock<https://github.com/Patrock>

This is by design, to stay close to spec with the builtin defaultdict from collections <https://docs.python.org/3.7/library/collections.html#defaultdict-objects>

>>> from collections import defaultdict
>>> my_dict = defaultdict(int)
>>> my_dict['key1']
0

>>> my_dict
defaultdict(<class 'int'>, {'key1': 0})

>>> my_dict.pop('key2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'key2'


However I will leave this open for now to consider it as a feature request.

**Comment by cdgriffith** [comment]
I think it would be best to add this as a full on box feature, that way both `pop` and `del` would not error if a key doesn't exist.
