### ISSUE TITLE
Deafault value in case of key not found

### ISSUE THREAD

**Issue by fessacchiotto** [cdgriffith/Box#69]
Thank you for your software! 

Is there a way to receive a `None`, or a default value, rather than a `BoxKeyError` like we could in: `get(key, default)` if the key is not found in the `Box`?

**Comment by cdgriffith** [comment]
Hi @fessacchiotto , 

There is the ability to use `default_box` and you can specify which parameter to have returned, by default it is an empty box (to enable multiple levels of returns). 

```python
>>> from box import Box
>>> my_box = Box(a=1, key_2=4, default_box=True)
>>> my_box.fake_key
<Box: {}>
>>> my_box.fake_key.another_fake_key
<Box: {}>
```

Be aware that if you do change it to `None` you can only have that behavior at the top most level.  

```python
>>> my_box = Box(a=1, default_box=True, default_box_attr=None)
>>>
>>> my_box.g  # Returns None as expected

>>> my_box.g.g.g  # Will error because it is looking for the attribute 'g' from the top most `None` object
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'g'
```

**Comment by fessacchiotto** [comment]
Thank you!
