### ISSUE TITLE
Rename methods

### ISSUE THREAD

**Issue by ololoe** [cdgriffith/Box#74]
I thing you should add _ to box' methods to prevent collisions, like it's done at namedtuple.

**Comment by cdgriffith** [comment]
Personally I disagree: 

1. Box is mature enough that this would be a major breaking change for many using it
2. There are only [6 custom functions](https://github.com/cdgriffith/Box#boxs-functions), and they do not have common key names
3. It is still possible to assign/access items with those names
```
>>> a = Box(to_json='test')
>>> a['to_json']
'test'
```

**Comment by ololoe** [comment]
I see much more

    d.asd        d.from_json  d.items      d.setdefault d.update
    d.box_it_up  d.from_yaml  d.keys       d.to_dict    d.values
    d.clear      d.fromkeys   d.pop        d.to_json    
    d.copy       d.get        d.popitem    d.to_yaml

Compared to namedtuple

    n.count n.index

**Comment by cdgriffith** [comment]
Those others are the base methods built into `dict` objects, of which `Box` is a subclass of.

```python
from box import Box
set(dir(Box())) - set(dir(dict()))
{'from_yaml', 'from_json', 'to_json', 'to_dict', 'box_it_up', 'to_yaml'}
```

**Comment by ololoe** [comment]
But your box behave like a namedtuple.

**Comment by cdgriffith** [comment]
That was never its intention, its title is literally "Python dictionaries with advanced dot notation access."

The first paragraph it the overview states it well: 

> Box is designed to be an easy drop in transparently replacements for dictionaries, thanks to Python's duck typing capabilities, which adds dot notation access. Any sub dictionaries or ones set after initiation will be automatically converted to a Box object. You can always run .to_dict() on it to return the object and all sub objects back into a regular dictionary.

**Comment by ololoe** [comment]
But dict methods break the "dot notation access", that's why I mentioned namedtuple...

I recently ran on this in django. `object.items` in templates called `object.items()` instead of getting `object['items']`

**Comment by cdgriffith** [comment]
I have no power to override the default dict methods like `items` and this is expected behavior.  If there is some magic way to access something as both an attribute and a method I would love a PR to enhance box to be able to do both.

**Comment by ololoe** [comment]
Then inheriting dict is probably wrong way...
