### ISSUE TITLE
Ability to recast the type of parameter(s)

### ISSUE THREAD

**Issue by SteveMcGrath** [cdgriffith/Box#76]
I'd look at this as almost a way to subclass Box and specify fields to recast.  For example:
```
class Example(Box):
    _recast_params = {
        'id': int,
        'settings.group.id': int
    }
```

**Comment by cdgriffith** [comment]
This is an interesting idea, and I almost think it could be two totally different additions: 

1. `Box(..., box_type=int)` introduce a way to autoconvert everything in the box (other than other box style objects) to a specific type. 

2. `Box(..., box_recast={'id': int})` and would recast any matching keys (include sub keys) as a particular type.

**Comment by SteveMcGrath** [comment]
option 2 is of more interest to me, as ideally I'd like to subclass box and use it fir the purpose of recasting attributes from APIs.  It would save me a lot of recasting code, and in keeping it generic, you could also wrap functions around things like arrow to recast as a datetime, etc.

**Comment by cdgriffith** [comment]
Added in 4.0
