### ISSUE TITLE
Keep object extended from dict/list intact

### ISSUE THREAD

**Issue by pwwang** [cdgriffith/Box#78]
Hi @cdgriffith,

I am the one who proposed `ordered_box`.  
I was recently bothered by `Box` turning some objects that are inherited from `dict/list` into `Box/BoxList`.  
Consider the following codes:

```python
from box import Box

class MyList(list): 
    def sq(self):
        return [x*x for x in self]
	
b = Box(a = MyList([1,2,4]))
b.a.sq()
# AttributeError: 'BoxList' object has no attribute 'sq'
# Expect [1,4,16]
```

I extended `list` to add some extra methods for convenience. However, when it was changed by `Box` into a `BoxList`, then I lost my method `sq`.
Is it possible to keep the objects of extended `dict/list` intact, but convert the raw `dict/list`s?   

One simple way is to check the `__bases__`, if it is `(object, )` then it should be a raw `dict/list`:
```python
def _israwinstance(obj, klass):
    return isinstance(obj, klass) and obj.__class__.__bases__ \
       and obj.__class__.__bases__[0] is object
```

Thanks,
Panwen

**Comment by cdgriffith** [comment]
I like the idea, it adds a nice touch of `klass`. 

What I am afraid of is that it is a subtle yet possibly game braking change. As there are many things that might be a subclass of dict that this is supposed to magically make easier to access (admittedly that up to this point would have overwritten those exiting custom objects.)

I would much prefer it to be enabled via a new `kwarg` setting. Bad examples - `box_soft_touch`, `dont_box_me_in` or `box_keep_modified_objects`.  As I find it much more likely that if you are using objects you don't want overwritten, you would know you need to look for an option to do so. Verses by default some of the magic being ripped away.

**Comment by cdgriffith** [comment]
Thinking about it a bit more, I think this could be good behavior for the next major release of Box 4.0, as I would feel comfortable adding breaking changes then.  (such as Python 3.6+ only with typewriting and the works).

So for time being would still appreciate needing that extra parameter, while working towards this being the new default.

**Comment by pwwang** [comment]
I understood your concern about not converting those subclasses of `dict` in this way, for example, `OrderedDict`.  
What about we enabling a `kwarg` setting, say `box_intact_types`, to put those types, and excluding them in `__convert_and_store`. My case would be then:
```python
from box import Box

class MyList(list): 
    def sq(self):
        return [x*x for x in self]
	
b = Box(a = MyList([1,2,4]), box_intact_types = (MyList, ))
b.a.sq()
# Expect [1,4,16]
```

In `__convert_and_store` while checking types, we could do:
```python
if isinstance(value, tuple(self._box_config['intact_types'])):
    return value
```

**Comment by cdgriffith** [comment]
I think that is an elegant solution!

Would switch the forced `tuple` on when `intact_types` is being set vs every time that is called, but other than that small thing, I really like it!

**Comment by cdgriffith** [comment]
Version 3.4.0 released https://github.com/cdgriffith/Box/commit/5f09df824022127e7e335e3d993f7ddc1ed97fce
