### ISSUE TITLE
Auto attributes creation

### ISSUE THREAD

**Issue by jhermann** [cdgriffith/Box#9]
```py
>>> b = box.Box()
>>> b.o.x = 42
AttributeError: 'Box' object has no attribute 'o'
```

IMHO this should work, possibly via a subtype (`AutoBox`) or `__init__` keyword arg (`auto_attr=True`).

Another variant would be ``OpenBox`` combined with a `close()` method – i.e. allow path construction initially, but then switch to default mode (`AttributeError`) after construction.

**Comment by cdgriffith** [comment]
I'm personally leaning towards doing keyword arguments, as that would allow for other customization and expansions in the future. I am mulling over how best to name them (so they aren't close to anything someone might have in a dictionary).

Either something like `box_auto_attr` or `_auto_attr`. Potentially add a `box_auto_default=Box` field as well so it's possible to make it more like a true default dict that a user can specify what type of object the default fallback is. 

Closing https://github.com/cdgriffith/Box/issues/5 as it was less detailed

**Comment by jhermann** [comment]
Sounds like separation of creating Box variants from using them would be valuable (separate namespaces with no awkward avoidance of overlap). So how about this:

```py
@box.closable
@box.autoattr
class MyClosableAutoBox(Box):
    """Customized ``Box``."""
```

Chances are you want to use such a beast at several places anyway, and then you'd have to curry the Box construction with those keyword args. :grimacing: 

Alas, Python3 only, but you could call the decorators explicitly in Python2.

**Comment by cdgriffith** [comment]
It's own namespace would be nice and simple, but for https://github.com/cdgriffith/Box/issues/6 need to have some sort of namespace pollution anyways, so I have been working on a way to make it near invisible. https://github.com/cdgriffith/Box/blob/auto_attr/box.py#L269

```python

my_box = Box({"I call Hax!": "totally"}, default_box=True, conversion_box=True)
my_box.i_call_hax
# Out[8]: 'totally'

my_box.sub_box.another_box.boxes_the_whole_way_down = 'Yet another box'
my_box
# Out[10]: <Box: {'I call Hax!': 'totally', 'sub_box': {'another_box': {'boxes_the_whole_way_down': 'Yet another box'}}}>
```

Could still make it into it's own subclass if those same options will always be repeated (still mulling over just adding a few of these as well for simplicity): 

```python
class DefaultBox(Box):
    def __init__(self, *args, **kwargs):
        super(Box, self).__init__(*args, **kwargs)
        self._box_config['default'] = True 
```

Thoughts?

**Comment by cdgriffith** [comment]
added `default_box` in 3.0 https://github.com/cdgriffith/Box/commit/6d90e4213365b66585de60676d317a80fe2607bc
