### ISSUE TITLE
Box options not propagated when using setdefault / append

### ISSUE THREAD

**Issue by str3tch** [cdgriffith/Box#95]
I have the code below.. should it work?

I can see why it is failing. The initial Box is set with default_box=True. Later, I add an array and append an empty object object. When I do this, I am not able to use the default_box functionality, and just keep on dot'ing down the Box

Easier to explain in code:

```
    a = Box(default_box=True)
    a.b.c.setdefault('d',[])
    a.b.c.d.append({})
    a.b.c.d[0].e.f = 1

...
>        if self._box_config['default_box']:
>              return self.__get_default(item)
>           raise BoxKeyError(str(err))
E           BoxKeyError: "'Box' object has no attribute 'e'"
> AttributeError: 'BoxList' object has no attribute 'e'
```

I can see why - the new box which was appended, appears not to be set with default_box=True

I tried this, thinking it would fix it, but it does not:

```
    a = Box(default_box=True)
    a.b.c.setdefault('d',[])
    a.b.c.d.append(Box(default_box=True))
    a.b.c.d[0].e.f = 1

> AttributeError: 'BoxList' object has no attribute 'e'
```

Is what I am attempting possible? I need to create big Elasticsearch json queries, which have nested arrays of objects. It is ugly to deal with in normal python, but Box really looks like it can help - apart from this issue. 

It looks like the original box_options are not propagated when using append. I can see in box.py that the parent options are not passed to BoxList (line 672 and 815) - I attempted a hotfix to pass them in, but didn't seem to work..

**Comment by cdgriffith** [comment]
Yeah, it definitively seems to be something I messed up / missed with `setdefault`, as it does propagate correctly otherwise. 

```
a.b.c.d = []
a.b.c.d.append({}) 
a.b.c.d[0].e
# <Box: {}>
```

Earliest I can dedicate time to this is probably late next week (major family stuff going on), but I will look into it as soon as I can!

**Comment by str3tch** [comment]
I see what the problem is... I'll raise a PR

**Comment by str3tch** [comment]
PR raised: https://github.com/cdgriffith/Box/pull/96

Hopefully this is the right way to fix it, I think it is :)

**Comment by cdgriffith** [comment]
Thanks again for the report and great PR! 

Adding to 3.4.3 https://github.com/cdgriffith/Box/pull/99
